name: daily export
#on:
#  schedule:
#  	- cron: '0 2 * * *'
on:
  push:

env:
  TZ: 'Asia/Tokyo'
  TW_UNAME: 'Ekusuwada' 
  HT_ID: 'kusuwada'
  HT_ROOT: 'kusuwada.hatenadiary.com'

jobs:
  daily:
    name: Daily Export
    runs-on: ubuntu-latest
    steps:
      - name: Get Time
        run: echo "DATE=$(date --date '1 day ago' +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Chekout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run Main
        run: |
          export TW_CK=${{ secrets.TW_CK }}
          export TW_CKS=${{ secrets.TW_CKS }}
          export TW_AT=${{ secrets.TW_AT }}
          export TW_ATS=${{ secrets.TW_ATS }}
          export HT_KEY=${{ secrets.HT_KEY }}          
          pip install -r requests.txt
          python daily.py $DATE $TW_UNAME $HT_ID $HT_ROOT ${{ runner.temp }} --tz=$TZ